### ISSUE TITLE
Unable to store data in WSO2AM_STATS_DB (Oracle)

### ISSUE THREAD

**Issue by vpatel-info** [ruks/WSO2-APIM_DAS_Analytics_CApp#2]
Hello Rukshan,

I am using your application for collecting data from WSO2 API manager 1.9.0 and store it in Oracle with DAS 3.0.0.

I am following http://blog.rukspot.com/2015/09/publishing-apim-runtime-statistics-to.html

We can see data in DAS's carbon dashboard in Data Explorer tables ORG_WSO2_APIMGT_STATISTICS_REQUEST and ORG_WSO2_APIMGT_STATISTICS_RESPONSE.

But data is not stored in Oracle. Therefore I am not able to see Statistics in publisher of AM. It keeps saying "Data publishing is enabled. Generate some traffic to see statistics."

I am getting following error in log:

[2015-12-08 13:00:00,022]  INFO {org.wso2.carbon.analytics.spark.core.AnalyticsT
ask} -  Executing the schedule task for: APIM_STAT_script for tenant id: -1234
[2015-12-08 13:00:00,037]  INFO {org.wso2.carbon.analytics.spark.core.AnalyticsT
ask} -  Executing the schedule task for: Throttle_script for tenant id: -1234
Exception in thread "dag-scheduler-event-loop" java.lang.NoClassDefFoundError: o
rg/xerial/snappy/SnappyInputStream
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:274)
        at org.apache.spark.io.CompressionCodec$.createCodec(CompressionCodec.sc
ala:66)
        at org.apache.spark.io.CompressionCodec$.createCodec(CompressionCodec.sc
ala:60)
        at org.apache.spark.broadcast.TorrentBroadcast.org$apache$spark$broadcas
t$TorrentBroadcast$$setConf(TorrentBroadcast.scala:73)
        at org.apache.spark.broadcast.TorrentBroadcast.<init>(TorrentBroadcast.s
cala:80)
        at org.apache.spark.broadcast.TorrentBroadcastFactory.newBroadcast(Torre
ntBroadcastFactory.scala:34)
        at org.apache.spark.broadcast.BroadcastManager.newBroadcast(BroadcastMan
ager.scala:62)
        at org.apache.spark.SparkContext.broadcast(SparkContext.scala:1291)
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DA
GScheduler$$submitMissingTasks(DAGScheduler.scala:874)
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DA
GScheduler$$submitStage(DAGScheduler.scala:815)
        at org.apache.spark.scheduler.DAGScheduler.handleJobSubmitted(DAGSchedul
er.scala:799)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAG
Scheduler.scala:1426)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAG
Scheduler.scala:1418)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
Caused by: java.lang.ClassNotFoundException: org.xerial.snappy.SnappyInputStream
 cannot be found by spark-core_2.10_1.4.1.wso2v1
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(Bundl
eLoader.java:501)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.
java:421)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.
java:412)
        at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(De
faultClassLoader.java:107)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 15 more

Am I missing something?
Can you please help me to figure out this issue?

Thanks in advance.

**Comment by ruks** [comment]
Hi,

can you attach the full logs please.

**Comment by ruks** [comment]
Hi,

DAS team suspect that it could be due to missing jar in classpath.
They are suggest following workaround.
- add the following line to the repository/conf/analytics/spark/external-spark-classpath.conf file 
        repository/components/plugins/org.xerial.snappy.snappy-java_1.1.1.7.jar

Thanks

**Comment by vpatel-info** [comment]
Thanks for your response.

Actually I added snappy-java-1.1.2-RC3.jar in repository/components/lib and its working fine now,
